DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_ID_SQ;

CREATE TABLE FRIEND (
  ID NUMBER(10),
  NAME VARCHAR2(30) NOT NULL,
  TEL VARCHAR2(20) UNIQUE,
  PRIMARY KEY(ID)
);

CREATE SEQUENCE FRIEND_ID_SQ MAXVALUE 9999999999 NOCACHE NOCYCLE;


-- MAPPER(REPOSITORY)에 들어갈 QUERY
-- ID = save
INSERT INTO FRIEND VALUES(FRIEND_ID_SQ.NEXTVAL, '홍길동', '010-0000-0000');
-- ID = findByTel
SELECT * FROM FRIEND WHERE TEL = '010-0000-0000';
-- ID = findAll
SELECT * FROM FRIEND;
-- ID = findById
SELECT * FROM FRIEND WHERE ID = 1;
-- ID = deleteAll
DELETE FROM FRIEND;
-- ID = deleteOne
DELETE FROM FRIEND WHERE ID = 2;

COMMIT;
