-- DROP & CREATE SEQUENCE, TABLE
DROP TABLE FILEBOARD;
DROP TABLE CUSTOMER;
DROP TABLE BOOK;
DROP SEQUENCE FILEBOARD_SEQ;
DROP SEQUENCE BOOK_SEQ;

CREATE TABLE BOOK (
  BID NUMBER(7) PRIMARY KEY,
  BTITLE VARCHAR2(100) NOT NULL,
  BPRICE NUMBER(6) NOT NULL,
  BIMG1 VARCHAR2(100) NOT NULL,
  BIMG2 VARCHAR2(100) NOT NULL,
  BCONTENT CLOB NOT NULL,
  BDISCOUNT NUMBER(3) NOT NULL,
  BRDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE BOOK_SEQ
  MAXVALUE 9999999
  NOCACHE
  NOCYCLE;

CREATE TABLE CUSTOMER (
  CID VARCHAR2(50) PRIMARY KEY,
  CPW VARCHAR2(50) NOT NULL,
  CNAME VARCHAR2(50) NOT NULL,
  CTEL VARCHAR2(50),
  CEMAIL VARCHAR2(50),
  CADDRESS VARCHAR2(50),
  CBIRTH DATE,
  CGENDER VARCHAR2(1),
  CRDATE DATE DEFAULT SYSDATE
);

CREATE TABLE FILEBOARD (
  FID NUMBER(6) PRIMARY KEY,
  CID VARCHAR2(50) REFERENCES CUSTOMER(CID) NOT NULL,
  FTITLE VARCHAR2(100) NOT NULL,
  FCONTENT CLOB,
  FILENAME VARCHAR2(100),
  FHIT NUMBER(6) DEFAULT 0,
  FPW VARCHAR2(50) NOT NULL,
  FGROUP NUMBER(6) NOT NULL,
  FSTEP NUMBER(2) NOT NULL,
  FINDENT NUMBER(2) NOT NULL,
  FIP VARCHAR2(50) NOT NULL,
  FRDATE DATE DEFAULT SYSDATE  NOT NULL
);

CREATE SEQUENCE FILEBOARD_SEQ 
  MAXVALUE 999999
  NOCACHE
  NOCYCLE;

SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM FILEBOARD;