-- DROP & CREATE SEQUENCE, TABLE
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
  CID VARCHAR2(50) PRIMARY KEY,
  CPW VARCHAR2(50) NOT NULL,
  CNAME VARCHAR2(50) NOT NULL,
  CTEL VARCHAR2(50),
  CEMAIL VARCHAR2(50),
  CADDRESS VARCHAR2(50),
  CBIRTH DATE,
  CGENDER VARCHAR2(1),
  CRDATE DATE DEFAULT SYSDATE
);

SELECT * FROM CUSTOMER;

-- DUMMY DATA INSERT
INSERT INTO CUSTOMER (CID, CPW, CNAME, CTEL, CEMAIL, CADDRESS, CBIRTH, CGENDER) VALUES ('hong', '123', '홍길동', '010-1234-5678', 'hong@naver.com', '서울 송파구', '1995-09-04', 'm');
