    -- 트랜잭션 명령어 : COMMIT(반영), ROLLBACK(취소), SAVEPOINT(분할)
    
DROP TABLE DEPT01;
CREATE TABLE DEPT01
    AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;

COMMIT;
----------------------------------NEW TRANSACTION
SELECT * FROM DEPT01; -- 10, 20, 30 ,40

DELETE FROM DEPT01 WHERE DEPTNO=20; -- 10, 30, 40
DELETE FROM DEPT01 WHERE DEPTNO=30; -- 10, 40
    
ROLLBACK; 
----------------------------------NEW TRANSACTION
SELECT * FROM DEPT01; -- 10, 20, 30, 40

DELETE FROM DEPT01 WHERE DEPTNO=40;

COMMIT;
----------------------------------NEW TRANSACTION
SELECT * FROM DEPT01; -- 10, 20, 30

DELETE FROM DEPT01 WHERE DEPTNO=30;

SELECT * FROM DEPT01;

SAVEPOINT C1; -- C1지점 : 10, 20

DELETE FROM DEPT01 WHERE DEPTNO=20;

SELECT * FROM DEPT01;

SAVEPOINT C2; -- C2지점 : 10

DELETE FROM DEPT01 WHERE DEPTNO=10;

SELECT * FROM DEPT01;

ROLLBACK TO C2; -- C2지점 이후만 취소

SELECT * FROM DEPT01;

ROLLBACK TO C1; -- C1지점 이후만 취소

SELECT * FROM DEPT01;

COMMIT;

SELECT * FROM DEPT01;
