
  -- SEQUENCE 삭제 & 생성 --
DROP SEQUENCE MEMBER_MNO_SQ;

CREATE SEQUENCE MEMBER_MNO_SQ
  MAXVALUE 999
  NOCACHE
  NOCYCLE;
  
  -- MEMBER, MEMBER_LEVEL 테이블 삭제 & 생성
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL ( 
  LEVELNO NUMBER(3) PRIMARY KEY,
  LEVELNAME VARCHAR2(10) NOT NULL
  );
  
CREATE TABLE MEMBER (
  mNO NUMBER(3) PRIMARY KEY,
  mNAME VARCHAR2(30) NOT NULL,
  mPW VARCHAR2(8),
  mEMAIL VARCHAR2(30) UNIQUE,
  mPOINT NUMBER(30) CHECK(mPOINT >=0),
  mRDATE DATE DEFAULT SYSDATE,
  LEVELNO NUMBER(3) REFERENCES MEMBER_LEVEL(LEVELNO)
  );
  
  -- 데이터 입력 --
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (2, '골드');


INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO) VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '22/03/10',  0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO) VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, '22/04/01',  1);

  -- 데이터 출력 --
SELECT mNO NO, mNAME 이름, TO_CHAR(mRDATE, 'YYYY-MM-DD') 가입일, mEMAIL 이메일, mPOINT POINT, LEVELNAME||'고객' 고객등급
 FROM MEMBER M, MEMBER_LEVEL L
 WHERE M.LEVELNO = L.LEVELNO;
  

  
  
  
  
  
  
  
  
  
  