-- DROP TABLE & SEQUENCE / CREATE TABLE & SEQUENCE
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD (
  BID NUMBER(6) PRIMARY KEY,
  BNAME VARCHAR2(50) NOT NULL,
  BTITLE VARCHAR2(100) NOT NULL,
  BCONTENT VARCHAR2(1000),
  BEMAIL VARCHAR2(50),
  BHIT NUMBER(6) DEFAULT 0 NOT NULL,
  BPW VARCHAR2(50) NOT NULL,
  BGROUP NUMBER(6) NOT NULL,
  BSTEP NUMBER(3) NOT NULL,
  BINDENT NUMBER(3) NOT NULL,
  BIP VARCHAR2(20) NOT NULL,
  BDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE BOARD_SEQ
  MAXVALUE 999999
  NOCACHE
  NOCYCLE
;

SELECT * FROM BOARD;
-- DUMMY DATA
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
        VALUES (BOARD_SEQ.NEXTVAL, 'HONG', '글1', 'CONTENT', 'NULL', '111', BOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
        VALUES (BOARD_SEQ.NEXTVAL, 'KIM', '글2', 'CONTENT2', 'NULL', '222', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
   
-- SQL QUERY
-- 1. 글목록(전체 글 그룹 최신순)
SELECT * FROM BOARD ORDER BY BGROUP DESC;
-- 1. 글목록(Startrow ~ EndRow)
SELECT * FROM BOARD ORDER BY BGROUP DESC;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A; -- TOP-N 구분 전단계
SELECT *
  FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A)
  WHERE RN BETWEEN 211 AND 220; -- 최종 QUERY


-- 2. 전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;
-- 3. 원글 쓰기 [작성자, 글제목, 본분, 이메일, 비밀번호, IP, BGORUP: 글번호, BTEP: 0, BINDENT: 0]
--INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
--        VALUES (BOARD_SEQ.NEXTVAL, 'KIM', 'TITLE2', 'CONTENT2', 'NULL', '222', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
-- 4. BID로 조회수 올리기 (글 상세보기)
UPDATE BOARD SET BHIT=BHIT+1 WHERE BID=1;
-- 5. BID로 DTO 받기(글 상세보기)
-- 6. BID로 DTO 받기(글 수정FORM, 답변글쓰기FORM)
SELECT * FROM BOARD WHERE BID=1;
-- 7. 글 수정(작성자, 글제목, 본문, 이메일, 비번, IP 수정)
UPDATE BOARD SET
      BNAME = '홍길동',
      BTITLE = '글1',
      BCONTENT = '이거슨 새로작성된 글이 아니라 수정된 글',
      BEMAIL = 'HONG@HONG.COM',
      BPW = '111',
      BIP = '192.168.0.1'
      WHERE BID=1;
-- 8. 글 삭제(비밀번호 일치 시에만 동작)
DELETE FROM BOARD WHERE BID=3 AND BPW='222';
-- 9. 답글 달기 
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
  VALUES (BOARD_SEQ.NEXTVAL, '박','글3', '냉무', NULL, '111', BOARD_SEQ.CURRVAL, 0, 0, '124.0.21.6');

SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;

-- 글 1-1
-- 엑셀 A단계(답변 글 쓰기 전 BSTEP 조정단계)
UPDATE BOARD SET BSTEP = BSTEP+1
  WHERE BGROUP=1 AND BSTEP>0;
-- 답변글 INSERT
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
  VALUES (BOARD_SEQ.NEXTVAL, 'DONG','글1-1', '냉무', NULL, '111', 1, 1, 1, '124.0.21.6');
  
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;
-- 글 2-1
-- 엑셀 A단계(답변 글 쓰기 전 BSTEP 조정단계)
UPDATE BOARD SET BSTEP=BSTEP+1
  WHERE BGROUP=2 AND BSTEP>0;
-- 답변글 INSERT
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
  VALUES (BOARD_SEQ.NEXTVAL, 'DONG','글2-1', '냉무', NULL, '111', 2, 1, 1, '124.0.21.42');
  
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;
-- 글 2-2
-- 엑셀 A단계(답변 글 쓰기 전 BSTEP 조정단계)
UPDATE BOARD SET BSTEP=BSTEP+1
  WHERE BGROUP=2 AND BSTEP>0;
-- 답변글 INSERT
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
  VALUES (BOARD_SEQ.NEXTVAL, 'DONG','글2-2', '냉무', NULL, '111', 2, 1, 1, '124.0.21.42');
  
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;
-- 글 2-2-1(6번글의 답변글)
-- 1. 글 목록에서 ORDER BY 부분 추가
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP) A) WHERE RN BETWEEN 2 AND 4; 
-- 엑셀 A단계(답변 글 쓰기 전 BSTEP 조정단계)
UPDATE BOARD SET BSTEP=BSTEP+1
  WHERE BGROUP=2 AND BSTEP>1;
-- 답변글 INSERT
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
  VALUES (BOARD_SEQ.NEXTVAL, 'DONG','글2-2-1', '냉무', NULL, '111', 2, 2, 2, '124.0.21.42');
  
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;

COMMIT;


