 -- DDL & DUMMY DATA
 
    -- TABLE & SEQ DROP --
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_PNO_SEQ;

    -- TABLE & SEQ CREATE --
CREATE TABLE JOB (
    jNO NUMBER(2,0) PRIMARY KEY,
    jNAME VARCHAR2(30) UNIQUE
    );
    
CREATE SEQUENCE PERSON_PNO_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
    
CREATE TABLE PERSON (
    pNO NUMBER(5) PRIMARY KEY,
    pNAME VARCHAR2(30) NOT NULL,
    jNO NUMBER(2,0) REFERENCES JOB(jNO) NOT NULL,
    KOR NUMBER(3) CHECK(KOR >= 0 AND KOR <= 100),
    ENG NUMBER(3) CHECK(ENG >= 0 AND ENG <= 100),
    MAT NUMBER(3) CHECK(MAT >= 0 AND MAT <= 100)
    );

SELECT * FROM JOB;
SELECT * FROM PERSON;
    
    
    -- DUMMY DATA INSERT --
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '개그맨');

SELECT * FROM JOB;

INSERT INTO PERSON VALUES (PERSON_PNO_SEQ.NEXTVAL, '정우성', 10,  90, 80, 91);
INSERT INTO PERSON VALUES (PERSON_PNO_SEQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_PNO_SEQ.NEXTVAL, '배수지', 20, 20, 90, 90);

SELECT * FROM PERSON;

COMMIT;






















