    -- DML
    
    -- 1번,2번 수행시 입력가능한 직업명을 사용자에게 출력
SELECT JNAME FROM JOB;
    
    
    
    -- 1번 기능 : PNAME, JNAME, KOR, ENG. MAT 입력받아 PERSON 테이블에 INSERT
INSERT INTO PERSON VALUES (PERSON_PNO_SEQ.NEXTVAL, '홍길동', (SELECT JNO FROM JOB WHERE JNAME='배우'), 99, 99, 100);

SELECT * FROM PERSON;

ROLLBACK;
COMMIT;
    -- 2번 기능 : JNAME 입력받아, RANK, PNAME(PNO), JNAME, KOR, ENG, MAT, SUM 출력
SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO AND JNAME='배우'
    ORDER BY SUM DESC;   -- INLINE 뷰에 들어갈 내용

SELECT ROWNUM RANK, A.*
    FROM (SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
          FROM PERSON P, JOB J
          WHERE P.JNO=J.JNO AND JNAME='배우'
          ORDER BY SUM DESC) A;

    -- 3번 기능 : RANK, PNAME(PNO), JNAME, KOR, ENG, MAT, SUM 출력
SELECT ROWNUM RANK, A.*
    FROM (SELECT PNAME||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
          FROM PERSON P, JOB J
          WHERE P.JNO=J.JNO
          ORDER BY SUM DESC) A;    
    
    
    