-- DROP TABLE & SEQUENCE / CREATE TABLE & SEQUENCE
DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD (
  BID NUMBER(6) PRIMARY KEY,
  BNAME VARCHAR2(50) NOT NULL,
  BTITLE VARCHAR2(100) NOT NULL,
  BCONTENT VARCHAR2(1000),
  BEMAIL VARCHAR2(50),
  BHIT NUMBER(6) DEFAULT 0 NOT NULL,
  BPW VARCHAR2(50) NOT NULL,
  BGROUP NUMBER(6) NOT NULL,
  BSTEP NUMBER(3) NOT NULL,
  BINDENT NUMBER(3) NOT NULL,
  BIP VARCHAR2(20) NOT NULL,
  BDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE BOARD_SEQ
  MAXVALUE 999999
  NOCACHE
  NOCYCLE
;

SELECT * FROM BOARD;
-- DUMMY DATA
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
        VALUES (BOARD_SEQ.NEXTVAL, 'HONG', 'TITLE', 'CONTENT', 'NULL', '111', BOARD_SEQ.CURRVAL, 0, 0, '192.168.0.1');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
        VALUES (BOARD_SEQ.NEXTVAL, 'KIM', 'TITLE2', 'CONTENT2', 'NULL', '222', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
        
-- SQL QUERY
-- 1. 글목록(전체 글 그룹 최신순)
SELECT * FROM BOARD ORDER BY BGROUP DESC;
-- 1. 글목록(Startrow ~ EndRow)
SELECT * FROM BOARD ORDER BY BGROUP DESC;
SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A; -- TOP-N 구분 전단계
SELECT *
  FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A)
  WHERE RN BETWEEN 211 AND 220; -- 최종 QUERY


-- 2. 전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;
-- 3. 원글 쓰기 [작성자, 글제목, 본분, 이메일, 비밀번호, IP, BGORUP: 글번호, BTEP: 0, BINDENT: 0]
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP)
        VALUES (BOARD_SEQ.NEXTVAL, 'KIM', 'TITLE2', 'CONTENT2', 'NULL', '222', BOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');
-- 4. BID로 조회수 올리기 (글 상세보기)
UPDATE BOARD SET BHIT=BHIT+1 WHERE BID=186;
-- 5. BID로 DTO 받기(글 상세보기)
-- 6. BID로 DTO 받기(글 수정FORM, 답변글쓰기FORM)
SELECT * FROM BOARD WHERE BID=3;
-- 7. 글 수정(작성자, 글제목, 본문, 이메일, 비번, IP 수정)
UPDATE BOARD SET
      BNAME = '홍길동',
      BTITLE = '바꾼제목',
      BCONTENT = '이거슨 새로작성된 글이 아니라 수정된 글',
      BEMAIL = 'HONG@HONG.COM',
      BPW = '111',
      BIP = '192.168.0.1'
      WHERE BID=1;
-- 8. 글 삭제(비밀번호 일치 시에만 동작)
DELETE FROM BOARD WHERE BID=3 AND BPW='222';



COMMIT;
