CREATE DATABASE ANIMAL;
USE ANIMAL;
-- MEMBER TABLE --
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
	ID VARCHAR(20) PRIMARY KEY,
    PW VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    TEL1 VARCHAR(10),
    TEL2 VARCHAR(10),
    TEL3 VARCHAR(10),
    EMAIL VARCHAR(50) NOT NULL,
    NICKNAME VARCHAR(20),
    ANAME VARCHAR(50),
    ADATE DATE,
    ADDRESS VARCHAR(200),
    RDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- DOG TABLE
DROP TABLE DOG;
CREATE TABLE DOG (
	DOGID INT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(20) NOT NULL,
    DOGNAME VARCHAR(50) NOT NULL,
    DOGTYPE VARCHAR(50) NOT NULL,
    DOGAGE NUMERIC(2) NOT NULL,
    DOGPRICE VARCHAR(10) NOT NULL,
    DOGIMG BLOB,
    DOGUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);
-- CAT TABLE
DROP TABLE CAT;
CREATE TABLE CAT (
	CATID INT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(20) NOT NULL,
    CATNAME VARCHAR(50) NOT NULL,
    CATTYPE VARCHAR(50) NOT NULL,
    CATAGE NUMERIC(2) NOT NULL,
    CATPRICE VARCHAR(10) NOT NULL,
    CATIMG BLOB,
    CATUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);
-- NOTICE TABLE
DROP TABLE NOTICE;
CREATE TABLE NOTICE (
	NNO INT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(20) NOT NULL,
    NDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NTITLE VARCHAR(50) NOT NULL,
    NTEXT BLOB,
    NIMG BLOB,
    NIP VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);




-- TABLE CHECK
SELECT * FROM MEMBER;
SELECT * FROM DOG;
SELECT * FROM CAT;
SELECT * FROM NOTICE;

