-- DROP & CREATE FOR SEQUENCE ~ TABLE
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ
  MAXVALUE 999999999
  NOCYCLE
  NOCACHE;
  
DROP TABLE FRIEND;
CREATE TABLE FRIEND (
  NO NUMBER(9) PRIMARY KEY,
  NAME VARCHAR2(20),
  TEL VARCHAR2(20) UNIQUE
);

SELECT * FROM FRIEND;
-- SQL QUERY
-- 1. INSERT
INSERT INTO FRIEND (NO, NAME, TEL) VALUES (FRIEND_NO_SEQ.NEXTVAL, 'HONG','010-12131334-5678');
INSERT INTO FRIEND (NO, NAME, TEL) VALUES (FRIEND_NO_SEQ.NEXTVAL, 'HONG','010-231-5679');

-- 2. SELECT
SELECT * FROM FRIEND ORDER BY NO;
commit;