-- TABLE DROP & CREATE
DROP TABLE MVC_MEMBER;

CREATE TABLE MVC_MEMBER (
  MID VARCHAR2(30) PRIMARY KEY,
  MPW VARCHAR2(30) NOT NULL,
  MNAME VARCHAR2(30) NOT NULL,
  MEMAIL VARCHAR2(30),
  MBIRTH DATE,
  MADDRESS VARCHAR2(300),
  MRDATE DATE DEFAULT SYSDATE NOT NULL
);

SELECT * FROM MVC_MEMBER;

-- 1. ID Confirm
SELECT * FROM MVC_MEMBER WHERE MID = 'AAA';
-- 2. Join
INSERT INTO MVC_MEMBER (MID, MPW, MNAME, MEMAIL, MBIRTH, MADDRESS)
  VALUES ('AAA', '111', 'HONG', 'HONG@EMAIL.COM', '2023/10/09', 'SEOUL');
-- 3. Login Check
SELECT * FROM MVC_MEMBER WHERE MID = 'AAA' AND MPW = '111';
-- 4. Session Dto init
SELECT * FROM MVC_MEMBER WHERE MID = 'AAA';



commit;