 -- DROP TABLE & SEQ
DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUSTOMER_CID_SQ;
 
 -- CREATE TABLE & SEQ
CREATE SEQUENCE CUSTOMER_CID_SQ
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE TABLE CUS_LEVEL (
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL,
    LOW NUMBER(9) NOT NULL,
    HIGH NUMBER(9) NOT NULL
    );
    
CREATE TABLE CUSTOMER (
    cID NUMBER(9) PRIMARY KEY,
    cTEL VARCHAR2(50) UNIQUE,
    cNAME VARCHAR2(30) NOT NULL,
    POINT NUMBER(9) DEFAULT 1000 NOT NULL CHECK(POINT >= 0),
    cAMOUNT NUMBER(9) DEFAULT 0,
    LEVELNO NUMBER(1) DEFAULT 1 REFERENCES CUS_LEVEL(LEVELNO),
    cMEMO VARCHAR2(1000)
    );


    
 
 -- INSERT DUMMY DATA
